/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 * Imports
 */
import java.io.*;
import java.util.*;
import java.awt.Image;
import java.awt.Toolkit;

/**
 * Implementation of my Menu class for the interface
 * @author Axel Daniel Malváez Flores
 * @version 1.0
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Attributes of the Menu
     */
    private File[] arrDocs;
    private ArrayList<String>[] stringList;
    private Hashtable<String, Pair<String, Double>> ht;
    private ArrayList<Pair<String,Double>>[] arrTF;
    private ArrayList<Pair<String,Double>>[] arrTFIDF;
    private ArrayList<Pair<ArrayList<String>, ArrayList<String>>> cache;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        arrDocs = null;
        stringList = null;
        ht = null;
        arrTF = null;
        arrTFIDF = null;
        cache = new ArrayList<Pair<ArrayList<String>, ArrayList<String>>>();
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method changes the icon of the interface
     */
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logoMD.png"));
        return retValue;
    }

    public void setArrDocs(File[] arrDocs) {
        this.arrDocs = arrDocs;
    }

    public void setStringList(ArrayList<String>[] stringList) {
        this.stringList = stringList;
    }

    public void setHt(Hashtable<String, Pair<String, Double>> ht) {
        this.ht = ht;
    }

    public void setArrTF(ArrayList<Pair<String, Double>>[] arrTF) {
        this.arrTF = arrTF;
    }

    public void setArrTFIDF(ArrayList<Pair<String, Double>>[] arrTFIDF) {
        this.arrTFIDF = arrTFIDF;
    }

    public void setCache(ArrayList<Pair<ArrayList<String>, ArrayList<String>>> cache) {
        this.cache = cache;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        Historial = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        cambiarRuta = new javax.swing.JButton();
        busquedaExplanation = new javax.swing.JLabel();
        historialExplanation = new javax.swing.JLabel();
        cambioRutaExplanation = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setFont(new java.awt.Font("Orator Std", 0, 36)); // NOI18N
        Menu.setText("MENÚ");
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 90, 60));

        Buscar.setBackground(new java.awt.Color(102, 102, 102));
        Buscar.setFont(new java.awt.Font("Orator Std", 0, 12)); // NOI18N
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Búsqueda");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 130, 50));

        Historial.setBackground(new java.awt.Color(102, 102, 102));
        Historial.setFont(new java.awt.Font("Orator Std", 0, 12)); // NOI18N
        Historial.setForeground(new java.awt.Color(255, 255, 255));
        Historial.setText("Historial");
        Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialActionPerformed(evt);
            }
        });
        getContentPane().add(Historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 130, 50));

        Salir.setBackground(new java.awt.Color(102, 102, 102));
        Salir.setFont(new java.awt.Font("Orator Std", 0, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 110, 30));

        cambiarRuta.setBackground(new java.awt.Color(102, 102, 102));
        cambiarRuta.setFont(new java.awt.Font("Orator Std", 0, 12)); // NOI18N
        cambiarRuta.setForeground(new java.awt.Color(255, 255, 255));
        cambiarRuta.setText("Cambiar de Ruta");
        cambiarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarRutaActionPerformed(evt);
            }
        });
        getContentPane().add(cambiarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 250, 50));

        busquedaExplanation.setFont(new java.awt.Font("Orator Std", 0, 12)); // NOI18N
        busquedaExplanation.setText("Hacer una búsqueda --->");
        getContentPane().add(busquedaExplanation, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        historialExplanation.setFont(new java.awt.Font("Orator Std", 0, 12)); // NOI18N
        historialExplanation.setText("<--- Ver el historial de búsqueda");
        getContentPane().add(historialExplanation, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, 20));

        cambioRutaExplanation.setFont(new java.awt.Font("Orator Std", 0, 12)); // NOI18N
        cambioRutaExplanation.setText("Cambiar de ruta --->");
        getContentPane().add(cambioRutaExplanation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frame1.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 356));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        Buscar busqueda = new Buscar();
      
        /* Agregar atributos */
        busqueda.setArrDocs(arrDocs);
        busqueda.setArrTF(arrTF);
        busqueda.setArrTFIDF(arrTFIDF);
        busqueda.setCache(cache);
        busqueda.setStringList(stringList);
        busqueda.setHt(ht);
        
        busqueda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BuscarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void cambiarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarRutaActionPerformed
        Interfaz inter = new Interfaz();
        inter.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cambiarRutaActionPerformed

    private void HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialActionPerformed
        Reader reader = new Reader();
        String historial = reader.readDocument("HistorialDeBusqueda.txt");
        //Create an Historial Frame
        Historial hist = new Historial(historial);
        hist.setArrDocs(arrDocs);
        hist.setArrTF(arrTF);
        hist.setArrTFIDF(arrTFIDF);
        hist.setCache(cache);
        hist.setHt(ht);
        hist.setStringList(stringList);
        
        //Display it.
        hist.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Historial;
    private javax.swing.JLabel Menu;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel busquedaExplanation;
    private javax.swing.JButton cambiarRuta;
    private javax.swing.JLabel cambioRutaExplanation;
    private javax.swing.JLabel historialExplanation;
    // End of variables declaration//GEN-END:variables
}
